/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.14.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>
#include "mycombobox.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLabel *labelMS;
    QCheckBox *checkBoxPeriodicSend;
    QGroupBox *groupBoxComSet;
    QPushButton *pushButtonOpen;
    myComboBox *comboBoxNo;
    QRadioButton *radioButton_led;
    QComboBox *comboBoxStop;
    QComboBox *comboBoxCheck;
    QComboBox *comboBoxComBaud;
    QComboBox *comboBoxData;
    QLabel *labelBaud;
    QLabel *labelData;
    QLabel *labelStop;
    QLabel *labelCheck;
    QGroupBox *groupBoxSendSet;
    QPushButton *pushButtonRdFile;
    QPushButton *pushButtonClearSend;
    QCheckBox *checkBoxSendHex;
    QCheckBox *checkBoxAddNewShift;
    QCheckBox *checkBoxAutoDownload;
    QGroupBox *groupBoxRevSet;
    QPushButton *pushButtonSaveRev;
    QPushButton *pushButtonStopRev;
    QPushButton *pushButtonClearRev;
    QCheckBox *checkBoxReVTime;
    QCheckBox *checkBoxRevHex;
    QGroupBox *groupBox;
    QPlainTextEdit *SubPacketText;
    QComboBox *comboBoxSubPacket;
    QGroupBox *groupBoxSend;
    QPlainTextEdit *TextSend;
    QPushButton *pushButtonSend;
    QGroupBox *groupBoxRev;
    QTextBrowser *TextRev;
    QPlainTextEdit *TextRevcpy;
    QRadioButton *radioButton;
    QGroupBox *groupBoxMutiSend;
    QLabel *label_3;
    QLabel *label;
    QLabel *label_2;
    QLineEdit *lineEditMuti8;
    QCheckBox *checkBoxMuti_4;
    QLineEdit *lineEditMuti2;
    QPushButton *pushButtonMuti1;
    QLineEdit *lineEditMuti10;
    QCheckBox *checkBoxMuti_7;
    QCheckBox *checkBoxMuti_8;
    QPushButton *pushButtonMuti4;
    QCheckBox *checkBoxMuti_6;
    QCheckBox *checkBoxMuti_2;
    QLineEdit *lineEditMuti9;
    QLineEdit *lineEditMuti3;
    QPushButton *pushButtonMuti9;
    QCheckBox *checkBoxMuti_9;
    QLineEdit *lineEditMuti5;
    QPushButton *pushButtonMuti2;
    QLineEdit *lineEditMuti1;
    QPushButton *pushButtonMuti6;
    QCheckBox *checkBoxMuti_1;
    QPushButton *pushButtonMuti5;
    QLineEdit *lineEditMuti6;
    QPushButton *pushButtonMuti7;
    QCheckBox *checkBoxMuti_5;
    QLineEdit *lineEditMuti4;
    QPushButton *pushButtonMuti3;
    QCheckBox *checkBoxMuti_3;
    QPushButton *pushButtonMuti10;
    QPushButton *pushButtonMuti8;
    QCheckBox *checkBoxMuti_10;
    QLineEdit *lineEditMuti7;
    QPushButton *pushButtonMutiReset;
    QCheckBox *checkBoxPeriodicMutiSend;
    QPushButton *pushButton_RYISP;
    QPushButton *pushButton_EraseAll;
    QPushButton *pushButton_WriteBin;
    QPushButton *pushButton_HexToBin;
    QPushButton *pushButton_Ymodem;
    QPushButton *pushButton_ESP32ISP;
    QGroupBox *groupBox_esp32;
    QPushButton *pushButton_Open_BOOT_Combine;
    QPushButton *pushButton_Open_PART;
    QPushButton *pushButton_Open_APP;
    QLineEdit *lineEdit_BOOT_Combine;
    QLineEdit *lineEdit_PART;
    QLineEdit *lineEdit_APP;
    QComboBox *comboBoxCheck_ESP32;
    QRadioButton *radioButton_combine;
    QLabel *label_BOOT_Combine;
    QLabel *label_PART;
    QLabel *label_APP;
    QPushButton *pushButton_ESP32_START;
    QProgressBar *progressBar_PART;
    QProgressBar *progressBar_BOOT_Combine;
    QProgressBar *progressBar_APP;
    QGroupBox *groupBox_stm32;
    QPushButton *pushButton_STM32_START;
    QRadioButton *radioButton_EraseALL;
    QRadioButton *radioButton_NotErase;
    QLineEdit *lineEditMuti_binaddr;
    QPushButton *pushButton_OpenBin;
    QProgressBar *progressBar;
    QLineEdit *lineEditMuti_FileName;
    QLabel *label_PART_2;
    QLineEdit *lineEditTime;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(728, 944);
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        MainWindow->setMinimumSize(QSize(0, 0));
        MainWindow->setMaximumSize(QSize(16777215, 16777215));
        MainWindow->setDockNestingEnabled(false);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        labelMS = new QLabel(centralWidget);
        labelMS->setObjectName(QString::fromUtf8("labelMS"));
        labelMS->setGeometry(QRect(690, 370, 41, 20));
        QFont font;
        font.setPointSize(9);
        labelMS->setFont(font);
        checkBoxPeriodicSend = new QCheckBox(centralWidget);
        checkBoxPeriodicSend->setObjectName(QString::fromUtf8("checkBoxPeriodicSend"));
        checkBoxPeriodicSend->setGeometry(QRect(580, 372, 71, 16));
        checkBoxPeriodicSend->setCheckable(true);
        groupBoxComSet = new QGroupBox(centralWidget);
        groupBoxComSet->setObjectName(QString::fromUtf8("groupBoxComSet"));
        groupBoxComSet->setGeometry(QRect(10, 0, 171, 201));
        pushButtonOpen = new QPushButton(groupBoxComSet);
        pushButtonOpen->setObjectName(QString::fromUtf8("pushButtonOpen"));
        pushButtonOpen->setGeometry(QRect(70, 170, 91, 22));
        comboBoxNo = new myComboBox(groupBoxComSet);
        comboBoxNo->setObjectName(QString::fromUtf8("comboBoxNo"));
        comboBoxNo->setGeometry(QRect(10, 30, 151, 22));
        QFont font1;
        font1.setPointSize(11);
        comboBoxNo->setFont(font1);
        comboBoxNo->setLayoutDirection(Qt::LeftToRight);
        comboBoxNo->setSizeAdjustPolicy(QComboBox::AdjustToMinimumContentsLengthWithIcon);
        comboBoxNo->setMinimumContentsLength(0);
        radioButton_led = new QRadioButton(groupBoxComSet);
        radioButton_led->setObjectName(QString::fromUtf8("radioButton_led"));
        radioButton_led->setGeometry(QRect(20, 160, 31, 41));
        radioButton_led->setStyleSheet(QString::fromUtf8("QRadioButton::indicator:checked{background-color:red;}\n"
"QRadioButton::indicator:unchecked{background-color:black;}\n"
"QRadioButton::indicator{width:25px;height:25px;border-radius:12px;}"));
        radioButton_led->setCheckable(true);
        radioButton_led->setChecked(false);
        radioButton_led->setAutoExclusive(false);
        comboBoxStop = new QComboBox(groupBoxComSet);
        comboBoxStop->addItem(QString());
        comboBoxStop->addItem(QString());
        comboBoxStop->addItem(QString());
        comboBoxStop->setObjectName(QString::fromUtf8("comboBoxStop"));
        comboBoxStop->setGeometry(QRect(70, 113, 91, 22));
        comboBoxStop->setFont(font1);
        comboBoxCheck = new QComboBox(groupBoxComSet);
        comboBoxCheck->addItem(QString());
        comboBoxCheck->addItem(QString());
        comboBoxCheck->addItem(QString());
        comboBoxCheck->addItem(QString());
        comboBoxCheck->addItem(QString());
        comboBoxCheck->setObjectName(QString::fromUtf8("comboBoxCheck"));
        comboBoxCheck->setGeometry(QRect(70, 139, 91, 22));
        comboBoxCheck->setFont(font1);
        comboBoxComBaud = new QComboBox(groupBoxComSet);
        comboBoxComBaud->addItem(QString());
        comboBoxComBaud->addItem(QString());
        comboBoxComBaud->addItem(QString());
        comboBoxComBaud->addItem(QString());
        comboBoxComBaud->addItem(QString());
        comboBoxComBaud->addItem(QString());
        comboBoxComBaud->addItem(QString());
        comboBoxComBaud->addItem(QString());
        comboBoxComBaud->addItem(QString());
        comboBoxComBaud->addItem(QString());
        comboBoxComBaud->addItem(QString());
        comboBoxComBaud->addItem(QString());
        comboBoxComBaud->addItem(QString());
        comboBoxComBaud->addItem(QString());
        comboBoxComBaud->addItem(QString());
        comboBoxComBaud->setObjectName(QString::fromUtf8("comboBoxComBaud"));
        comboBoxComBaud->setEnabled(true);
        comboBoxComBaud->setGeometry(QRect(70, 60, 91, 22));
        comboBoxComBaud->setFont(font1);
        comboBoxData = new QComboBox(groupBoxComSet);
        comboBoxData->addItem(QString());
        comboBoxData->addItem(QString());
        comboBoxData->addItem(QString());
        comboBoxData->addItem(QString());
        comboBoxData->setObjectName(QString::fromUtf8("comboBoxData"));
        comboBoxData->setGeometry(QRect(70, 87, 91, 22));
        comboBoxData->setFont(font1);
        comboBoxData->setLayoutDirection(Qt::LeftToRight);
        labelBaud = new QLabel(groupBoxComSet);
        labelBaud->setObjectName(QString::fromUtf8("labelBaud"));
        labelBaud->setGeometry(QRect(11, 61, 39, 18));
        labelData = new QLabel(groupBoxComSet);
        labelData->setObjectName(QString::fromUtf8("labelData"));
        labelData->setGeometry(QRect(11, 88, 39, 18));
        labelStop = new QLabel(groupBoxComSet);
        labelStop->setObjectName(QString::fromUtf8("labelStop"));
        labelStop->setGeometry(QRect(11, 115, 39, 18));
        labelCheck = new QLabel(groupBoxComSet);
        labelCheck->setObjectName(QString::fromUtf8("labelCheck"));
        labelCheck->setGeometry(QRect(11, 141, 39, 18));
        comboBoxStop->raise();
        comboBoxCheck->raise();
        comboBoxComBaud->raise();
        comboBoxData->raise();
        labelBaud->raise();
        labelData->raise();
        labelStop->raise();
        labelCheck->raise();
        pushButtonOpen->raise();
        comboBoxNo->raise();
        radioButton_led->raise();
        groupBoxSendSet = new QGroupBox(centralWidget);
        groupBoxSendSet->setObjectName(QString::fromUtf8("groupBoxSendSet"));
        groupBoxSendSet->setGeometry(QRect(10, 382, 171, 151));
        pushButtonRdFile = new QPushButton(groupBoxSendSet);
        pushButtonRdFile->setObjectName(QString::fromUtf8("pushButtonRdFile"));
        pushButtonRdFile->setGeometry(QRect(70, 25, 91, 22));
        pushButtonClearSend = new QPushButton(groupBoxSendSet);
        pushButtonClearSend->setObjectName(QString::fromUtf8("pushButtonClearSend"));
        pushButtonClearSend->setGeometry(QRect(70, 52, 91, 22));
        checkBoxSendHex = new QCheckBox(groupBoxSendSet);
        checkBoxSendHex->setObjectName(QString::fromUtf8("checkBoxSendHex"));
        checkBoxSendHex->setGeometry(QRect(76, 80, 101, 22));
        checkBoxAddNewShift = new QCheckBox(groupBoxSendSet);
        checkBoxAddNewShift->setObjectName(QString::fromUtf8("checkBoxAddNewShift"));
        checkBoxAddNewShift->setGeometry(QRect(76, 103, 101, 22));
        checkBoxAddNewShift->setCheckable(true);
        checkBoxAutoDownload = new QCheckBox(groupBoxSendSet);
        checkBoxAutoDownload->setObjectName(QString::fromUtf8("checkBoxAutoDownload"));
        checkBoxAutoDownload->setGeometry(QRect(76, 123, 101, 22));
        groupBoxRevSet = new QGroupBox(centralWidget);
        groupBoxRevSet->setObjectName(QString::fromUtf8("groupBoxRevSet"));
        groupBoxRevSet->setGeometry(QRect(10, 200, 171, 161));
        pushButtonSaveRev = new QPushButton(groupBoxRevSet);
        pushButtonSaveRev->setObjectName(QString::fromUtf8("pushButtonSaveRev"));
        pushButtonSaveRev->setGeometry(QRect(10, 20, 61, 21));
        pushButtonStopRev = new QPushButton(groupBoxRevSet);
        pushButtonStopRev->setObjectName(QString::fromUtf8("pushButtonStopRev"));
        pushButtonStopRev->setGeometry(QRect(10, 50, 61, 21));
        pushButtonClearRev = new QPushButton(groupBoxRevSet);
        pushButtonClearRev->setObjectName(QString::fromUtf8("pushButtonClearRev"));
        pushButtonClearRev->setGeometry(QRect(10, 80, 61, 21));
        checkBoxReVTime = new QCheckBox(groupBoxRevSet);
        checkBoxReVTime->setObjectName(QString::fromUtf8("checkBoxReVTime"));
        checkBoxReVTime->setGeometry(QRect(80, 20, 77, 22));
        checkBoxReVTime->setChecked(true);
        checkBoxRevHex = new QCheckBox(groupBoxRevSet);
        checkBoxRevHex->setObjectName(QString::fromUtf8("checkBoxRevHex"));
        checkBoxRevHex->setEnabled(true);
        checkBoxRevHex->setGeometry(QRect(80, 50, 77, 22));
        checkBoxRevHex->setCheckable(true);
        checkBoxRevHex->setChecked(true);
        checkBoxRevHex->setTristate(false);
        groupBox = new QGroupBox(groupBoxRevSet);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(10, 110, 151, 41));
        SubPacketText = new QPlainTextEdit(groupBox);
        SubPacketText->setObjectName(QString::fromUtf8("SubPacketText"));
        SubPacketText->setGeometry(QRect(0, 20, 151, 21));
        comboBoxSubPacket = new QComboBox(groupBox);
        comboBoxSubPacket->addItem(QString());
        comboBoxSubPacket->addItem(QString());
        comboBoxSubPacket->addItem(QString());
        comboBoxSubPacket->setObjectName(QString::fromUtf8("comboBoxSubPacket"));
        comboBoxSubPacket->setGeometry(QRect(30, 2, 91, 20));
        comboBoxSubPacket->setFont(font1);
        groupBoxSend = new QGroupBox(centralWidget);
        groupBoxSend->setObjectName(QString::fromUtf8("groupBoxSend"));
        groupBoxSend->setGeometry(QRect(180, 392, 541, 141));
        TextSend = new QPlainTextEdit(groupBoxSend);
        TextSend->setObjectName(QString::fromUtf8("TextSend"));
        TextSend->setEnabled(true);
        TextSend->setGeometry(QRect(10, 30, 521, 111));
        pushButtonSend = new QPushButton(groupBoxSend);
        pushButtonSend->setObjectName(QString::fromUtf8("pushButtonSend"));
        pushButtonSend->setGeometry(QRect(500, 120, 31, 21));
        pushButtonSend->setCheckable(false);
        pushButtonSend->setChecked(false);
        pushButtonSend->setAutoDefault(false);
        groupBoxRev = new QGroupBox(centralWidget);
        groupBoxRev->setObjectName(QString::fromUtf8("groupBoxRev"));
        groupBoxRev->setGeometry(QRect(180, 0, 341, 361));
        TextRev = new QTextBrowser(groupBoxRev);
        TextRev->setObjectName(QString::fromUtf8("TextRev"));
        TextRev->setGeometry(QRect(5, 11, 331, 341));
        TextRevcpy = new QPlainTextEdit(groupBoxRev);
        TextRevcpy->setObjectName(QString::fromUtf8("TextRevcpy"));
        TextRevcpy->setGeometry(QRect(160, 250, 171, 101));
        TextRevcpy->setLayoutDirection(Qt::LeftToRight);
        TextRevcpy->setReadOnly(true);
        radioButton = new QRadioButton(centralWidget);
        radioButton->setObjectName(QString::fromUtf8("radioButton"));
        radioButton->setGeometry(QRect(500, 372, 81, 16));
        radioButton->setAutoExclusive(false);
        groupBoxMutiSend = new QGroupBox(centralWidget);
        groupBoxMutiSend->setObjectName(QString::fromUtf8("groupBoxMutiSend"));
        groupBoxMutiSend->setGeometry(QRect(530, 0, 191, 361));
        label_3 = new QLabel(groupBoxMutiSend);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(160, 20, 31, 16));
        label = new QLabel(groupBoxMutiSend);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 20, 41, 16));
        label_2 = new QLabel(groupBoxMutiSend);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(60, 20, 61, 16));
        lineEditMuti8 = new QLineEdit(groupBoxMutiSend);
        lineEditMuti8->setObjectName(QString::fromUtf8("lineEditMuti8"));
        lineEditMuti8->setGeometry(QRect(30, 239, 121, 20));
        checkBoxMuti_4 = new QCheckBox(groupBoxMutiSend);
        checkBoxMuti_4->setObjectName(QString::fromUtf8("checkBoxMuti_4"));
        checkBoxMuti_4->setGeometry(QRect(9, 130, 16, 16));
        lineEditMuti2 = new QLineEdit(groupBoxMutiSend);
        lineEditMuti2->setObjectName(QString::fromUtf8("lineEditMuti2"));
        lineEditMuti2->setGeometry(QRect(30, 72, 121, 20));
        pushButtonMuti1 = new QPushButton(groupBoxMutiSend);
        pushButtonMuti1->setObjectName(QString::fromUtf8("pushButtonMuti1"));
        pushButtonMuti1->setGeometry(QRect(157, 42, 31, 23));
        lineEditMuti10 = new QLineEdit(groupBoxMutiSend);
        lineEditMuti10->setObjectName(QString::fromUtf8("lineEditMuti10"));
        lineEditMuti10->setGeometry(QRect(30, 299, 121, 20));
        checkBoxMuti_7 = new QCheckBox(groupBoxMutiSend);
        checkBoxMuti_7->setObjectName(QString::fromUtf8("checkBoxMuti_7"));
        checkBoxMuti_7->setGeometry(QRect(9, 215, 16, 16));
        checkBoxMuti_8 = new QCheckBox(groupBoxMutiSend);
        checkBoxMuti_8->setObjectName(QString::fromUtf8("checkBoxMuti_8"));
        checkBoxMuti_8->setGeometry(QRect(9, 242, 16, 16));
        pushButtonMuti4 = new QPushButton(groupBoxMutiSend);
        pushButtonMuti4->setObjectName(QString::fromUtf8("pushButtonMuti4"));
        pushButtonMuti4->setGeometry(QRect(158, 126, 31, 23));
        checkBoxMuti_6 = new QCheckBox(groupBoxMutiSend);
        checkBoxMuti_6->setObjectName(QString::fromUtf8("checkBoxMuti_6"));
        checkBoxMuti_6->setGeometry(QRect(9, 187, 16, 16));
        checkBoxMuti_2 = new QCheckBox(groupBoxMutiSend);
        checkBoxMuti_2->setObjectName(QString::fromUtf8("checkBoxMuti_2"));
        checkBoxMuti_2->setGeometry(QRect(9, 75, 16, 16));
        lineEditMuti9 = new QLineEdit(groupBoxMutiSend);
        lineEditMuti9->setObjectName(QString::fromUtf8("lineEditMuti9"));
        lineEditMuti9->setGeometry(QRect(31, 269, 121, 20));
        lineEditMuti3 = new QLineEdit(groupBoxMutiSend);
        lineEditMuti3->setObjectName(QString::fromUtf8("lineEditMuti3"));
        lineEditMuti3->setGeometry(QRect(30, 100, 121, 20));
        pushButtonMuti9 = new QPushButton(groupBoxMutiSend);
        pushButtonMuti9->setObjectName(QString::fromUtf8("pushButtonMuti9"));
        pushButtonMuti9->setGeometry(QRect(158, 267, 31, 23));
        checkBoxMuti_9 = new QCheckBox(groupBoxMutiSend);
        checkBoxMuti_9->setObjectName(QString::fromUtf8("checkBoxMuti_9"));
        checkBoxMuti_9->setGeometry(QRect(10, 272, 16, 16));
        lineEditMuti5 = new QLineEdit(groupBoxMutiSend);
        lineEditMuti5->setObjectName(QString::fromUtf8("lineEditMuti5"));
        lineEditMuti5->setGeometry(QRect(30, 156, 121, 20));
        pushButtonMuti2 = new QPushButton(groupBoxMutiSend);
        pushButtonMuti2->setObjectName(QString::fromUtf8("pushButtonMuti2"));
        pushButtonMuti2->setGeometry(QRect(158, 70, 31, 23));
        lineEditMuti1 = new QLineEdit(groupBoxMutiSend);
        lineEditMuti1->setObjectName(QString::fromUtf8("lineEditMuti1"));
        lineEditMuti1->setGeometry(QRect(30, 44, 121, 20));
        pushButtonMuti6 = new QPushButton(groupBoxMutiSend);
        pushButtonMuti6->setObjectName(QString::fromUtf8("pushButtonMuti6"));
        pushButtonMuti6->setGeometry(QRect(158, 182, 31, 23));
        checkBoxMuti_1 = new QCheckBox(groupBoxMutiSend);
        checkBoxMuti_1->setObjectName(QString::fromUtf8("checkBoxMuti_1"));
        checkBoxMuti_1->setGeometry(QRect(9, 47, 16, 16));
        pushButtonMuti5 = new QPushButton(groupBoxMutiSend);
        pushButtonMuti5->setObjectName(QString::fromUtf8("pushButtonMuti5"));
        pushButtonMuti5->setGeometry(QRect(158, 154, 31, 23));
        lineEditMuti6 = new QLineEdit(groupBoxMutiSend);
        lineEditMuti6->setObjectName(QString::fromUtf8("lineEditMuti6"));
        lineEditMuti6->setGeometry(QRect(30, 184, 121, 20));
        pushButtonMuti7 = new QPushButton(groupBoxMutiSend);
        pushButtonMuti7->setObjectName(QString::fromUtf8("pushButtonMuti7"));
        pushButtonMuti7->setGeometry(QRect(158, 210, 31, 23));
        checkBoxMuti_5 = new QCheckBox(groupBoxMutiSend);
        checkBoxMuti_5->setObjectName(QString::fromUtf8("checkBoxMuti_5"));
        checkBoxMuti_5->setGeometry(QRect(9, 159, 16, 16));
        lineEditMuti4 = new QLineEdit(groupBoxMutiSend);
        lineEditMuti4->setObjectName(QString::fromUtf8("lineEditMuti4"));
        lineEditMuti4->setGeometry(QRect(30, 127, 121, 20));
        pushButtonMuti3 = new QPushButton(groupBoxMutiSend);
        pushButtonMuti3->setObjectName(QString::fromUtf8("pushButtonMuti3"));
        pushButtonMuti3->setGeometry(QRect(158, 98, 31, 23));
        checkBoxMuti_3 = new QCheckBox(groupBoxMutiSend);
        checkBoxMuti_3->setObjectName(QString::fromUtf8("checkBoxMuti_3"));
        checkBoxMuti_3->setGeometry(QRect(9, 103, 16, 16));
        pushButtonMuti10 = new QPushButton(groupBoxMutiSend);
        pushButtonMuti10->setObjectName(QString::fromUtf8("pushButtonMuti10"));
        pushButtonMuti10->setGeometry(QRect(158, 297, 31, 23));
        pushButtonMuti8 = new QPushButton(groupBoxMutiSend);
        pushButtonMuti8->setObjectName(QString::fromUtf8("pushButtonMuti8"));
        pushButtonMuti8->setGeometry(QRect(158, 238, 31, 23));
        checkBoxMuti_10 = new QCheckBox(groupBoxMutiSend);
        checkBoxMuti_10->setObjectName(QString::fromUtf8("checkBoxMuti_10"));
        checkBoxMuti_10->setGeometry(QRect(9, 302, 16, 16));
        lineEditMuti7 = new QLineEdit(groupBoxMutiSend);
        lineEditMuti7->setObjectName(QString::fromUtf8("lineEditMuti7"));
        lineEditMuti7->setGeometry(QRect(30, 212, 121, 20));
        pushButtonMutiReset = new QPushButton(groupBoxMutiSend);
        pushButtonMutiReset->setObjectName(QString::fromUtf8("pushButtonMutiReset"));
        pushButtonMutiReset->setGeometry(QRect(10, 330, 31, 23));
        checkBoxPeriodicMutiSend = new QCheckBox(groupBoxMutiSend);
        checkBoxPeriodicMutiSend->setObjectName(QString::fromUtf8("checkBoxPeriodicMutiSend"));
        checkBoxPeriodicMutiSend->setGeometry(QRect(50, 330, 131, 23));
        checkBoxPeriodicMutiSend->setCheckable(true);
        pushButton_RYISP = new QPushButton(centralWidget);
        pushButton_RYISP->setObjectName(QString::fromUtf8("pushButton_RYISP"));
        pushButton_RYISP->setEnabled(true);
        pushButton_RYISP->setGeometry(QRect(260, 370, 91, 22));
        pushButton_RYISP->setAutoDefault(false);
        pushButton_EraseAll = new QPushButton(centralWidget);
        pushButton_EraseAll->setObjectName(QString::fromUtf8("pushButton_EraseAll"));
        pushButton_EraseAll->setGeometry(QRect(160, 690, 113, 32));
        pushButton_WriteBin = new QPushButton(centralWidget);
        pushButton_WriteBin->setObjectName(QString::fromUtf8("pushButton_WriteBin"));
        pushButton_WriteBin->setGeometry(QRect(40, 650, 113, 32));
        pushButton_HexToBin = new QPushButton(centralWidget);
        pushButton_HexToBin->setObjectName(QString::fromUtf8("pushButton_HexToBin"));
        pushButton_HexToBin->setGeometry(QRect(40, 690, 113, 32));
        pushButton_Ymodem = new QPushButton(centralWidget);
        pushButton_Ymodem->setObjectName(QString::fromUtf8("pushButton_Ymodem"));
        pushButton_Ymodem->setEnabled(false);
        pushButton_Ymodem->setGeometry(QRect(280, 700, 81, 21));
        pushButton_Ymodem->setAutoDefault(false);
        pushButton_ESP32ISP = new QPushButton(centralWidget);
        pushButton_ESP32ISP->setObjectName(QString::fromUtf8("pushButton_ESP32ISP"));
        pushButton_ESP32ISP->setEnabled(true);
        pushButton_ESP32ISP->setGeometry(QRect(370, 370, 91, 22));
        pushButton_ESP32ISP->setAutoDefault(false);
        groupBox_esp32 = new QGroupBox(centralWidget);
        groupBox_esp32->setObjectName(QString::fromUtf8("groupBox_esp32"));
        groupBox_esp32->setGeometry(QRect(180, 560, 531, 151));
        pushButton_Open_BOOT_Combine = new QPushButton(groupBox_esp32);
        pushButton_Open_BOOT_Combine->setObjectName(QString::fromUtf8("pushButton_Open_BOOT_Combine"));
        pushButton_Open_BOOT_Combine->setGeometry(QRect(120, 30, 101, 23));
        pushButton_Open_PART = new QPushButton(groupBox_esp32);
        pushButton_Open_PART->setObjectName(QString::fromUtf8("pushButton_Open_PART"));
        pushButton_Open_PART->setGeometry(QRect(120, 55, 101, 22));
        pushButton_Open_APP = new QPushButton(groupBox_esp32);
        pushButton_Open_APP->setObjectName(QString::fromUtf8("pushButton_Open_APP"));
        pushButton_Open_APP->setGeometry(QRect(120, 79, 101, 22));
        lineEdit_BOOT_Combine = new QLineEdit(groupBox_esp32);
        lineEdit_BOOT_Combine->setObjectName(QString::fromUtf8("lineEdit_BOOT_Combine"));
        lineEdit_BOOT_Combine->setGeometry(QRect(231, 32, 179, 21));
        lineEdit_PART = new QLineEdit(groupBox_esp32);
        lineEdit_PART->setObjectName(QString::fromUtf8("lineEdit_PART"));
        lineEdit_PART->setGeometry(QRect(231, 55, 179, 21));
        lineEdit_APP = new QLineEdit(groupBox_esp32);
        lineEdit_APP->setObjectName(QString::fromUtf8("lineEdit_APP"));
        lineEdit_APP->setGeometry(QRect(231, 78, 179, 21));
        comboBoxCheck_ESP32 = new QComboBox(groupBox_esp32);
        comboBoxCheck_ESP32->addItem(QString());
        comboBoxCheck_ESP32->addItem(QString());
        comboBoxCheck_ESP32->addItem(QString());
        comboBoxCheck_ESP32->addItem(QString());
        comboBoxCheck_ESP32->addItem(QString());
        comboBoxCheck_ESP32->addItem(QString());
        comboBoxCheck_ESP32->addItem(QString());
        comboBoxCheck_ESP32->addItem(QString());
        comboBoxCheck_ESP32->addItem(QString());
        comboBoxCheck_ESP32->setObjectName(QString::fromUtf8("comboBoxCheck_ESP32"));
        comboBoxCheck_ESP32->setGeometry(QRect(10, 30, 91, 21));
        comboBoxCheck_ESP32->setFont(font1);
        radioButton_combine = new QRadioButton(groupBox_esp32);
        radioButton_combine->setObjectName(QString::fromUtf8("radioButton_combine"));
        radioButton_combine->setGeometry(QRect(10, 60, 111, 16));
        radioButton_combine->setAutoExclusive(false);
        label_BOOT_Combine = new QLabel(groupBox_esp32);
        label_BOOT_Combine->setObjectName(QString::fromUtf8("label_BOOT_Combine"));
        label_BOOT_Combine->setGeometry(QRect(421, 31, 81, 16));
        label_PART = new QLabel(groupBox_esp32);
        label_PART->setObjectName(QString::fromUtf8("label_PART"));
        label_PART->setGeometry(QRect(421, 57, 64, 16));
        label_APP = new QLabel(groupBox_esp32);
        label_APP->setObjectName(QString::fromUtf8("label_APP"));
        label_APP->setGeometry(QRect(421, 82, 70, 16));
        pushButton_ESP32_START = new QPushButton(groupBox_esp32);
        pushButton_ESP32_START->setObjectName(QString::fromUtf8("pushButton_ESP32_START"));
        pushButton_ESP32_START->setGeometry(QRect(340, 100, 71, 20));
        progressBar_PART = new QProgressBar(groupBox_esp32);
        progressBar_PART->setObjectName(QString::fromUtf8("progressBar_PART"));
        progressBar_PART->setEnabled(true);
        progressBar_PART->setGeometry(QRect(230, 56, 181, 20));
        QSizePolicy sizePolicy1(QSizePolicy::Minimum, QSizePolicy::Fixed);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(progressBar_PART->sizePolicy().hasHeightForWidth());
        progressBar_PART->setSizePolicy(sizePolicy1);
        progressBar_PART->setMinimumSize(QSize(0, 0));
        QFont font2;
        font2.setPointSize(13);
        progressBar_PART->setFont(font2);
        progressBar_PART->setMouseTracking(false);
        progressBar_PART->setTabletTracking(false);
        progressBar_PART->setContextMenuPolicy(Qt::DefaultContextMenu);
        progressBar_PART->setAcceptDrops(false);
        progressBar_PART->setAutoFillBackground(true);
        progressBar_PART->setValue(0);
        progressBar_PART->setAlignment(Qt::AlignCenter);
        progressBar_PART->setTextVisible(true);
        progressBar_PART->setInvertedAppearance(false);
        progressBar_PART->setTextDirection(QProgressBar::TopToBottom);
        progressBar_BOOT_Combine = new QProgressBar(groupBox_esp32);
        progressBar_BOOT_Combine->setObjectName(QString::fromUtf8("progressBar_BOOT_Combine"));
        progressBar_BOOT_Combine->setEnabled(true);
        progressBar_BOOT_Combine->setGeometry(QRect(230, 30, 181, 20));
        sizePolicy1.setHeightForWidth(progressBar_BOOT_Combine->sizePolicy().hasHeightForWidth());
        progressBar_BOOT_Combine->setSizePolicy(sizePolicy1);
        progressBar_BOOT_Combine->setMinimumSize(QSize(0, 0));
        progressBar_BOOT_Combine->setFont(font2);
        progressBar_BOOT_Combine->setMouseTracking(false);
        progressBar_BOOT_Combine->setTabletTracking(false);
        progressBar_BOOT_Combine->setContextMenuPolicy(Qt::DefaultContextMenu);
        progressBar_BOOT_Combine->setAcceptDrops(false);
        progressBar_BOOT_Combine->setAutoFillBackground(true);
        progressBar_BOOT_Combine->setValue(0);
        progressBar_BOOT_Combine->setAlignment(Qt::AlignCenter);
        progressBar_BOOT_Combine->setTextVisible(false);
        progressBar_BOOT_Combine->setInvertedAppearance(false);
        progressBar_BOOT_Combine->setTextDirection(QProgressBar::TopToBottom);
        progressBar_APP = new QProgressBar(groupBox_esp32);
        progressBar_APP->setObjectName(QString::fromUtf8("progressBar_APP"));
        progressBar_APP->setEnabled(true);
        progressBar_APP->setGeometry(QRect(230, 80, 181, 19));
        sizePolicy1.setHeightForWidth(progressBar_APP->sizePolicy().hasHeightForWidth());
        progressBar_APP->setSizePolicy(sizePolicy1);
        progressBar_APP->setMinimumSize(QSize(0, 0));
        progressBar_APP->setFont(font2);
        progressBar_APP->setMouseTracking(false);
        progressBar_APP->setTabletTracking(false);
        progressBar_APP->setContextMenuPolicy(Qt::DefaultContextMenu);
        progressBar_APP->setAcceptDrops(false);
        progressBar_APP->setAutoFillBackground(true);
        progressBar_APP->setValue(0);
        progressBar_APP->setAlignment(Qt::AlignCenter);
        progressBar_APP->setTextVisible(true);
        progressBar_APP->setInvertedAppearance(false);
        progressBar_APP->setTextDirection(QProgressBar::TopToBottom);
        lineEdit_APP->raise();
        lineEdit_PART->raise();
        lineEdit_BOOT_Combine->raise();
        pushButton_Open_BOOT_Combine->raise();
        pushButton_Open_PART->raise();
        pushButton_Open_APP->raise();
        comboBoxCheck_ESP32->raise();
        radioButton_combine->raise();
        label_BOOT_Combine->raise();
        label_PART->raise();
        label_APP->raise();
        pushButton_ESP32_START->raise();
        progressBar_PART->raise();
        progressBar_BOOT_Combine->raise();
        progressBar_APP->raise();
        groupBox_stm32 = new QGroupBox(centralWidget);
        groupBox_stm32->setObjectName(QString::fromUtf8("groupBox_stm32"));
        groupBox_stm32->setGeometry(QRect(180, 720, 531, 151));
        pushButton_STM32_START = new QPushButton(groupBox_stm32);
        pushButton_STM32_START->setObjectName(QString::fromUtf8("pushButton_STM32_START"));
        pushButton_STM32_START->setGeometry(QRect(340, 90, 71, 21));
        radioButton_EraseALL = new QRadioButton(groupBox_stm32);
        radioButton_EraseALL->setObjectName(QString::fromUtf8("radioButton_EraseALL"));
        radioButton_EraseALL->setGeometry(QRect(10, 40, 71, 16));
        radioButton_EraseALL->setChecked(true);
        radioButton_NotErase = new QRadioButton(groupBox_stm32);
        radioButton_NotErase->setObjectName(QString::fromUtf8("radioButton_NotErase"));
        radioButton_NotErase->setGeometry(QRect(10, 60, 61, 16));
        lineEditMuti_binaddr = new QLineEdit(groupBox_stm32);
        lineEditMuti_binaddr->setObjectName(QString::fromUtf8("lineEditMuti_binaddr"));
        lineEditMuti_binaddr->setGeometry(QRect(330, 30, 81, 21));
        lineEditMuti_binaddr->setFont(font1);
        pushButton_OpenBin = new QPushButton(groupBox_stm32);
        pushButton_OpenBin->setObjectName(QString::fromUtf8("pushButton_OpenBin"));
        pushButton_OpenBin->setGeometry(QRect(180, 60, 61, 21));
        progressBar = new QProgressBar(groupBox_stm32);
        progressBar->setObjectName(QString::fromUtf8("progressBar"));
        progressBar->setEnabled(true);
        progressBar->setGeometry(QRect(250, 60, 161, 21));
        sizePolicy1.setHeightForWidth(progressBar->sizePolicy().hasHeightForWidth());
        progressBar->setSizePolicy(sizePolicy1);
        progressBar->setMinimumSize(QSize(0, 0));
        progressBar->setFont(font2);
        progressBar->setMouseTracking(false);
        progressBar->setTabletTracking(false);
        progressBar->setContextMenuPolicy(Qt::DefaultContextMenu);
        progressBar->setAcceptDrops(false);
        progressBar->setAutoFillBackground(true);
        progressBar->setValue(0);
        progressBar->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        progressBar->setTextVisible(true);
        progressBar->setInvertedAppearance(false);
        progressBar->setTextDirection(QProgressBar::TopToBottom);
        lineEditMuti_FileName = new QLineEdit(groupBox_stm32);
        lineEditMuti_FileName->setObjectName(QString::fromUtf8("lineEditMuti_FileName"));
        lineEditMuti_FileName->setGeometry(QRect(250, 60, 161, 21));
        label_PART_2 = new QLabel(groupBox_stm32);
        label_PART_2->setObjectName(QString::fromUtf8("label_PART_2"));
        label_PART_2->setGeometry(QRect(180, 30, 91, 16));
        lineEditMuti_FileName->raise();
        progressBar->raise();
        pushButton_STM32_START->raise();
        radioButton_EraseALL->raise();
        radioButton_NotErase->raise();
        lineEditMuti_binaddr->raise();
        pushButton_OpenBin->raise();
        label_PART_2->raise();
        lineEditTime = new QLineEdit(centralWidget);
        lineEditTime->setObjectName(QString::fromUtf8("lineEditTime"));
        lineEditTime->setGeometry(QRect(650, 370, 31, 16));
        QFont font3;
        font3.setPointSize(8);
        lineEditTime->setFont(font3);
        MainWindow->setCentralWidget(centralWidget);
        pushButton_EraseAll->raise();
        labelMS->raise();
        checkBoxPeriodicSend->raise();
        groupBoxComSet->raise();
        groupBoxSendSet->raise();
        groupBoxRevSet->raise();
        groupBoxSend->raise();
        groupBoxRev->raise();
        radioButton->raise();
        groupBoxMutiSend->raise();
        pushButton_RYISP->raise();
        pushButton_WriteBin->raise();
        pushButton_HexToBin->raise();
        pushButton_Ymodem->raise();
        pushButton_ESP32ISP->raise();
        groupBox_esp32->raise();
        groupBox_stm32->raise();
        lineEditTime->raise();
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 728, 23));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        mainToolBar->setFloatable(false);
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        statusBar->setSizeGripEnabled(true);
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        comboBoxComBaud->setCurrentIndex(0);
        comboBoxData->setCurrentIndex(3);
        pushButtonSend->setDefault(false);
        pushButton_RYISP->setDefault(false);
        pushButton_Ymodem->setDefault(true);
        pushButton_ESP32ISP->setDefault(false);
        comboBoxCheck_ESP32->setCurrentIndex(4);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "RYCOM\344\270\262\345\217\243\350\260\203\350\257\225\345\212\251\346\211\213V2.6.2 rymcu.com\345\265\214\345\205\245\345\274\217\347\237\245\350\257\206\345\255\246\344\271\240\344\272\244\346\265\201\345\271\263\345\217\260", nullptr));
        labelMS->setText(QCoreApplication::translate("MainWindow", "ms/\346\254\241", nullptr));
        checkBoxPeriodicSend->setText(QCoreApplication::translate("MainWindow", "\345\221\250\346\234\237\345\217\221\351\200\201", nullptr));
        groupBoxComSet->setTitle(QCoreApplication::translate("MainWindow", "\344\270\262\345\217\243\350\256\276\347\275\256", nullptr));
        pushButtonOpen->setText(QCoreApplication::translate("MainWindow", "\346\211\223\345\274\200\344\270\262\345\217\243", nullptr));
        radioButton_led->setText(QString());
        comboBoxStop->setItemText(0, QCoreApplication::translate("MainWindow", "1", nullptr));
        comboBoxStop->setItemText(1, QCoreApplication::translate("MainWindow", "1.5", nullptr));
        comboBoxStop->setItemText(2, QCoreApplication::translate("MainWindow", "2", nullptr));

        comboBoxCheck->setItemText(0, QCoreApplication::translate("MainWindow", "None", nullptr));
        comboBoxCheck->setItemText(1, QCoreApplication::translate("MainWindow", "Even", nullptr));
        comboBoxCheck->setItemText(2, QCoreApplication::translate("MainWindow", "Odd", nullptr));
        comboBoxCheck->setItemText(3, QCoreApplication::translate("MainWindow", "Mark", nullptr));
        comboBoxCheck->setItemText(4, QCoreApplication::translate("MainWindow", "Space", nullptr));

        comboBoxComBaud->setItemText(0, QCoreApplication::translate("MainWindow", "115200", nullptr));
        comboBoxComBaud->setItemText(1, QCoreApplication::translate("MainWindow", "1200", nullptr));
        comboBoxComBaud->setItemText(2, QCoreApplication::translate("MainWindow", "2400", nullptr));
        comboBoxComBaud->setItemText(3, QCoreApplication::translate("MainWindow", "4800", nullptr));
        comboBoxComBaud->setItemText(4, QCoreApplication::translate("MainWindow", "9600", nullptr));
        comboBoxComBaud->setItemText(5, QCoreApplication::translate("MainWindow", "19200", nullptr));
        comboBoxComBaud->setItemText(6, QCoreApplication::translate("MainWindow", "38400", nullptr));
        comboBoxComBaud->setItemText(7, QCoreApplication::translate("MainWindow", "57600", nullptr));
        comboBoxComBaud->setItemText(8, QCoreApplication::translate("MainWindow", "115200", nullptr));
        comboBoxComBaud->setItemText(9, QCoreApplication::translate("MainWindow", "230400", nullptr));
        comboBoxComBaud->setItemText(10, QCoreApplication::translate("MainWindow", "460800", nullptr));
        comboBoxComBaud->setItemText(11, QCoreApplication::translate("MainWindow", "576000", nullptr));
        comboBoxComBaud->setItemText(12, QCoreApplication::translate("MainWindow", "921600", nullptr));
        comboBoxComBaud->setItemText(13, QCoreApplication::translate("MainWindow", "1382400", nullptr));
        comboBoxComBaud->setItemText(14, QCoreApplication::translate("MainWindow", "\350\207\252\345\256\232\344\271\211", nullptr));

        comboBoxData->setItemText(0, QCoreApplication::translate("MainWindow", "5", nullptr));
        comboBoxData->setItemText(1, QCoreApplication::translate("MainWindow", "6", nullptr));
        comboBoxData->setItemText(2, QCoreApplication::translate("MainWindow", "7", nullptr));
        comboBoxData->setItemText(3, QCoreApplication::translate("MainWindow", "8", nullptr));

        labelBaud->setText(QCoreApplication::translate("MainWindow", "\346\263\242\347\211\271\347\216\207", nullptr));
        labelData->setText(QCoreApplication::translate("MainWindow", "\346\225\260\346\215\256\344\275\215", nullptr));
        labelStop->setText(QCoreApplication::translate("MainWindow", "\345\201\234\346\255\242\344\275\215", nullptr));
        labelCheck->setText(QCoreApplication::translate("MainWindow", "\346\240\241\351\252\214\344\275\215", nullptr));
        groupBoxSendSet->setTitle(QCoreApplication::translate("MainWindow", "\345\217\221\351\200\201\350\256\276\347\275\256", nullptr));
        pushButtonRdFile->setText(QCoreApplication::translate("MainWindow", "\350\257\273\345\217\226\346\226\207\344\273\266", nullptr));
        pushButtonClearSend->setText(QCoreApplication::translate("MainWindow", "\346\270\205\347\251\272\345\217\221\351\200\201\345\214\272", nullptr));
        checkBoxSendHex->setText(QCoreApplication::translate("MainWindow", "\345\215\201\345\205\255\350\277\233\345\210\266", nullptr));
        checkBoxAddNewShift->setText(QCoreApplication::translate("MainWindow", "\345\217\221\351\200\201\346\226\260\350\241\214", nullptr));
        checkBoxAutoDownload->setText(QCoreApplication::translate("MainWindow", "\350\207\252\345\220\257\345\212\250\344\270\213\350\275\275", nullptr));
        groupBoxRevSet->setTitle(QCoreApplication::translate("MainWindow", "\346\216\245\346\224\266\350\256\276\347\275\256", nullptr));
        pushButtonSaveRev->setText(QCoreApplication::translate("MainWindow", "\344\277\235\345\255\230\346\226\207\344\273\266", nullptr));
        pushButtonStopRev->setText(QCoreApplication::translate("MainWindow", "\346\230\276\347\244\272\344\270\255", nullptr));
        pushButtonClearRev->setText(QCoreApplication::translate("MainWindow", "\346\270\205\347\251\272\346\216\245\346\224\266\345\214\272", nullptr));
        checkBoxReVTime->setText(QCoreApplication::translate("MainWindow", "\346\216\245\346\224\266\346\227\266\351\227\264", nullptr));
        checkBoxRevHex->setText(QCoreApplication::translate("MainWindow", "\345\215\201\345\205\255\350\277\233\345\210\266", nullptr));
        groupBox->setTitle(QString());
        comboBoxSubPacket->setItemText(0, QString());
        comboBoxSubPacket->setItemText(1, QCoreApplication::translate("MainWindow", "\345\210\206\345\214\205", nullptr));
        comboBoxSubPacket->setItemText(2, QCoreApplication::translate("MainWindow", "\347\247\273\351\231\244\345\214\205", nullptr));

        groupBoxSend->setTitle(QCoreApplication::translate("MainWindow", "\345\217\221\351\200\201\345\214\272", nullptr));
        TextSend->setPlainText(QString());
        pushButtonSend->setText(QCoreApplication::translate("MainWindow", "\345\217\221\351\200\201", nullptr));
        groupBoxRev->setTitle(QCoreApplication::translate("MainWindow", "\346\216\245\346\224\266\345\214\272", nullptr));
        TextRevcpy->setPlainText(QString());
        radioButton->setText(QCoreApplication::translate("MainWindow", "\350\207\252\345\256\232\344\271\211\345\221\275\344\273\244", nullptr));
        groupBoxMutiSend->setTitle(QCoreApplication::translate("MainWindow", "\345\244\232\350\241\214\345\217\221\351\200\201\345\214\272", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "\345\217\221\351\200\201", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "\351\200\211\344\270\255", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "\350\276\223\345\205\245\345\255\227\347\254\246", nullptr));
        lineEditMuti8->setText(QCoreApplication::translate("MainWindow", "8", nullptr));
        checkBoxMuti_4->setText(QString());
        lineEditMuti2->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        pushButtonMuti1->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        lineEditMuti10->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        checkBoxMuti_7->setText(QString());
        checkBoxMuti_8->setText(QString());
        pushButtonMuti4->setText(QCoreApplication::translate("MainWindow", "4", nullptr));
        checkBoxMuti_6->setText(QString());
        checkBoxMuti_2->setText(QString());
        lineEditMuti9->setText(QCoreApplication::translate("MainWindow", "9", nullptr));
        lineEditMuti3->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        pushButtonMuti9->setText(QCoreApplication::translate("MainWindow", "9", nullptr));
        checkBoxMuti_9->setText(QString());
        lineEditMuti5->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        pushButtonMuti2->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        lineEditMuti1->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        pushButtonMuti6->setText(QCoreApplication::translate("MainWindow", "6", nullptr));
        checkBoxMuti_1->setText(QString());
        pushButtonMuti5->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        lineEditMuti6->setText(QCoreApplication::translate("MainWindow", "6", nullptr));
        pushButtonMuti7->setText(QCoreApplication::translate("MainWindow", "7", nullptr));
        checkBoxMuti_5->setText(QString());
        lineEditMuti4->setText(QCoreApplication::translate("MainWindow", "4", nullptr));
        pushButtonMuti3->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        checkBoxMuti_3->setText(QString());
        pushButtonMuti10->setText(QCoreApplication::translate("MainWindow", "10", nullptr));
        pushButtonMuti8->setText(QCoreApplication::translate("MainWindow", "8", nullptr));
        checkBoxMuti_10->setText(QString());
        lineEditMuti7->setText(QCoreApplication::translate("MainWindow", "7", nullptr));
        pushButtonMutiReset->setText(QCoreApplication::translate("MainWindow", "\345\244\215\344\275\215", nullptr));
        checkBoxPeriodicMutiSend->setText(QCoreApplication::translate("MainWindow", "\345\244\232\350\241\214\345\276\252\347\216\257\345\217\221\351\200\201", nullptr));
        pushButton_RYISP->setText(QCoreApplication::translate("MainWindow", "STM32\344\270\213\350\275\275", nullptr));
        pushButton_EraseAll->setText(QCoreApplication::translate("MainWindow", "EraseAll", nullptr));
        pushButton_WriteBin->setText(QCoreApplication::translate("MainWindow", "WriteBin", nullptr));
        pushButton_HexToBin->setText(QCoreApplication::translate("MainWindow", "HexToBin", nullptr));
        pushButton_Ymodem->setText(QCoreApplication::translate("MainWindow", "Ymodem", nullptr));
        pushButton_ESP32ISP->setText(QCoreApplication::translate("MainWindow", "ESP32\344\270\213\350\275\275", nullptr));
        groupBox_esp32->setTitle(QCoreApplication::translate("MainWindow", "ESP32\350\256\276\347\275\256", nullptr));
        pushButton_Open_BOOT_Combine->setText(QCoreApplication::translate("MainWindow", "\346\211\223\345\274\200BOOT", nullptr));
        pushButton_Open_PART->setText(QCoreApplication::translate("MainWindow", "\346\211\223\345\274\200PART", nullptr));
        pushButton_Open_APP->setText(QCoreApplication::translate("MainWindow", "\346\211\223\345\274\200APP", nullptr));
        lineEdit_BOOT_Combine->setText(QString());
        lineEdit_BOOT_Combine->setPlaceholderText(QCoreApplication::translate("MainWindow", "\351\200\211\346\213\251bootlaoder.bin", nullptr));
        lineEdit_PART->setText(QString());
        lineEdit_PART->setPlaceholderText(QCoreApplication::translate("MainWindow", "\351\200\211\346\213\251partition-table.bin", nullptr));
        lineEdit_APP->setText(QString());
        lineEdit_APP->setPlaceholderText(QCoreApplication::translate("MainWindow", "\351\200\211\346\213\251app.bin", nullptr));
        comboBoxCheck_ESP32->setItemText(0, QCoreApplication::translate("MainWindow", "ESP8266", nullptr));
        comboBoxCheck_ESP32->setItemText(1, QCoreApplication::translate("MainWindow", "ESP32", nullptr));
        comboBoxCheck_ESP32->setItemText(2, QCoreApplication::translate("MainWindow", "ESP32S2", nullptr));
        comboBoxCheck_ESP32->setItemText(3, QCoreApplication::translate("MainWindow", "ESP32C3", nullptr));
        comboBoxCheck_ESP32->setItemText(4, QCoreApplication::translate("MainWindow", "ESP32S3", nullptr));
        comboBoxCheck_ESP32->setItemText(5, QCoreApplication::translate("MainWindow", "ESP32C2", nullptr));
        comboBoxCheck_ESP32->setItemText(6, QCoreApplication::translate("MainWindow", "ESP32_RESERVED0_CHIP", nullptr));
        comboBoxCheck_ESP32->setItemText(7, QCoreApplication::translate("MainWindow", "ESP32H2", nullptr));
        comboBoxCheck_ESP32->setItemText(8, QCoreApplication::translate("MainWindow", "ESP32C6", nullptr));

        radioButton_combine->setText(QCoreApplication::translate("MainWindow", "\345\215\225\344\270\252\345\220\210\345\271\266\345\220\216bin", nullptr));
        label_BOOT_Combine->setText(QCoreApplication::translate("MainWindow", "@ 0x0", nullptr));
        label_PART->setText(QCoreApplication::translate("MainWindow", "@ 0x8000", nullptr));
        label_APP->setText(QCoreApplication::translate("MainWindow", "@ 0x10000", nullptr));
        pushButton_ESP32_START->setText(QCoreApplication::translate("MainWindow", "\345\220\257\345\212\250\344\270\213\350\275\275", nullptr));
        groupBox_stm32->setTitle(QCoreApplication::translate("MainWindow", "STM32\350\256\276\347\275\256", nullptr));
        pushButton_STM32_START->setText(QCoreApplication::translate("MainWindow", "\345\220\257\345\212\250\344\270\213\350\275\275", nullptr));
        radioButton_EraseALL->setText(QCoreApplication::translate("MainWindow", "\345\205\250\346\223\246\351\231\244", nullptr));
        radioButton_NotErase->setText(QCoreApplication::translate("MainWindow", "\344\270\215\346\223\246\351\231\244", nullptr));
        lineEditMuti_binaddr->setText(QCoreApplication::translate("MainWindow", "0x08000000", nullptr));
        pushButton_OpenBin->setText(QCoreApplication::translate("MainWindow", "\346\211\223\345\274\200\346\226\207\344\273\266", nullptr));
        lineEditMuti_FileName->setText(QString());
        lineEditMuti_FileName->setPlaceholderText(QCoreApplication::translate("MainWindow", "\351\200\211\346\213\251.Hex\346\210\226.bin\346\226\207\344\273\266", nullptr));
        label_PART_2->setText(QCoreApplication::translate("MainWindow", ".bin\350\265\267\345\247\213\345\234\260\345\235\200", nullptr));
        lineEditTime->setText(QCoreApplication::translate("MainWindow", "1000", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
